name: Upload Python Package to PyPI

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Mandatory for OIDC trusted publishing
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures all history is fetched, avoiding shallow clones
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Cache management
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: v1-pip-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          v1-pip-${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Clean old builds
      run: |
        rm -rf dist build *.egg-info
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
